Load Kaggle Data

In [12]:
import kagglehub
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import cv2


path = kagglehub.dataset_download("mahdinavaei/blood-cancer")

# The dataset contains images, not CSV files
dataset_dir = os.path.join(path, "bloodcells_dataset")

# List all cell types (directories)
cell_types = [d for d in os.listdir(dataset_dir) if os.path.isdir(os.path.join(dataset_dir, d))]
print("Cell types in the dataset:")
for cell_type in cell_types:
    cell_type_path = os.path.join(dataset_dir, cell_type)
    num_images = len([f for f in os.listdir(cell_type_path) if f.endswith('.jpg')])
    print(f"  {cell_type}: {num_images} images")

# If you need to work with the data as a DataFrame, you can create one
data = []
for cell_type in cell_types:
    cell_type_path = os.path.join(dataset_dir, cell_type)
    images = [f for f in os.listdir(cell_type_path) if f.endswith('.jpg')]
    for image in images:
        data.append({
            'cell_type': cell_type,
            'image_name': image,
            'image_path': os.path.join(cell_type_path, image)
        })

df = pd.DataFrame(data)
print(f"\nTotal images: {len(df)}")
df.head()

Cell types in the dataset:
  platelet: 2348 images
  eosinophil: 3117 images
  monocyte: 1420 images
  neutrophil: 3329 images
  basophil: 1218 images
  lymphocyte: 1214 images
  erythroblast: 1551 images
  ig: 2895 images

Total images: 17092

,cell_type,image_name,image_path
0,platelet,PLATELET_535376.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
1,platelet,PLATELET_657024.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
2,platelet,PLATELET_236448.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
3,platelet,PLATELET_227634.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
4,platelet,PLATELET_98108.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...

In [13]:
train_df, dummy_df = train_test_split(df,  train_size= 0.8, shuffle= True, random_state= 123)

valid_df, test_df = train_test_split(dummy_df,  train_size= 0.6, shuffle= True, random_state= 123)

In [ ]:
batch_size = 32
img_size = (224, 224)

channels = 3
img_shape = (img_size[0], img_size[1], channels)

train_df, dummy_df = train_test_split(df,  train_size= 0.8, shuffle= True, random_state= 123)

valid_df, test_df = train_test_split(dummy_df,  train_size= 0.6, shuffle= True, random_state= 123)




valid_df

,cell_type,image_name,image_path
17002,ig,MMY_752335.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
3085,eosinophil,EO_99246.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
13472,erythroblast,ERB_655342.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
1763,platelet,PLATELET_775368.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
19,platelet,PLATELET_627215.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
...,...,...,...
8471,neutrophil,BNE_506191.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
12314,lymphocyte,LY_703368.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
5017,eosinophil,EO_259587.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
15081,ig,MY_924222.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...
2407,eosinophil,EO_255525.jpg,/home/aroe/.cache/kagglehub/datasets/mahdinava...